import {StyleSheet, Dimensions} from 'react-native';

const {width: SCREEN_WIDTH, height: SCREEN_HEIGHT} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  gradientBackground: {
    flex: 1,
  },
  overlay01: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(252, 206, 232, 0.3)',
    right: 30,
    top: 250,
  },
  overlay02: {
    position: 'absolute',
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    left: 40,
    top: 100,
    opacity: 0.54,
  },
  headerContainer: {
    position: 'absolute',
    top: 44,
    left: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    zIndex: 100,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: 24,
    lineHeight: 36,
    color: '#FFFFFF',
    includeFontPadding: false,
  },
  headerSubtitle: {
    position: 'absolute',
    top: 92,
    left: 72,
    fontFamily: 'NotoSansKR-Medium',
    fontSize: 13,
    lineHeight: 19.5,
    color: 'rgba(255, 255, 255, 0.9)',
    includeFontPadding: false,
  },
  contentContainer: {
    position: 'absolute',
    top: 132,
    left: 0,
    right: 0,
    paddingHorizontal: 24,
    paddingVertical: 30,
    alignItems: 'center',
    gap: 32,
  },
  micButtonContainer: {
    width: 200,
    height: 200,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 25},
    shadowOpacity: 0.25,
    shadowRadius: 50,
    elevation: 10,
  },
  micButtonGradient: {
    width: 200,
    height: 200,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  micImage: {
    width: 100,
    height: 100,
  },
  instructionText: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: 18,
    lineHeight: 27,
    color: '#FFFFFF',
    includeFontPadding: false,
  },
  listeningText: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: 18,
    lineHeight: 27,
    color: '#FFFFFF',
    includeFontPadding: false,
  },
  timerText: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: 48,
    lineHeight: 60,
    color: '#FFFFFF',
    marginTop: 12,
    includeFontPadding: false,
  },
  resultContainer: {
    width: SCREEN_WIDTH - 48,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 20,
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 24,
    gap: 8,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 20},
    shadowOpacity: 0.1,
    shadowRadius: 25,
    elevation: 8,
  },
  resultLabel: {
    fontFamily: 'NotoSansKR-Medium',
    fontSize: 14,
    lineHeight: 21,
    color: '#525252',
    includeFontPadding: false,
  },
  resultText: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: 16,
    lineHeight: 24,
    color: '#36454F',
    includeFontPadding: false,
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 32,
    width: SCREEN_WIDTH - 48,
  },
  retryButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 44,
    paddingVertical: 16,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 20},
    shadowOpacity: 0.1,
    shadowRadius: 25,
    elevation: 8,
  },
  retryButtonText: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: 16,
    lineHeight: 24,
    color: '#404040',
    includeFontPadding: false,
  },
  nextButton: {
    paddingHorizontal: 40,
    paddingVertical: 16,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 25},
    shadowOpacity: 0.25,
    shadowRadius: 50,
    elevation: 10,
  },
  nextButtonText: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: 16,
    lineHeight: 24,
    color: '#FFFFFF',
    includeFontPadding: false,
  },
});
