import {StyleSheet} from 'react-native';
import {colors, spacing} from '../../common';

export default StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  container: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderGray,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textBlack,
    fontFamily: 'NotoSansKR-Bold',
  },
  content: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
  },
  locationBox: {
    backgroundColor: 'rgba(127, 201, 231, 0.1)',
    borderWidth: 1,
    borderColor: '#7FC9E7',
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 13,
    marginBottom: spacing.xl,
  },
  locationLabel: {
    fontSize: 12,
    color: colors.textGray,
    fontFamily: 'NotoSansKR-Regular',
    marginBottom: 4,
  },
  locationValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textBlack,
    fontFamily: 'NotoSansKR-Bold',
  },
  section: {
    marginBottom: spacing.xl,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: colors.textBlack,
    fontFamily: 'NotoSansKR-Bold',
    marginBottom: 10,
  },
  required: {
    fontSize: 15,
    fontWeight: 'bold',
    color: colors.error,
    fontFamily: 'NotoSansKR-Bold',
    marginLeft: 2,
  },
  timeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    borderWidth: 2,
    borderColor: colors.borderGray,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: spacing.lg,
  },
  timeButtonText: {
    fontSize: 14,
    color: colors.textBlack,
    fontFamily: 'NotoSansKR-Regular',
  },
  slider: {
    width: '100%',
    height: 40,
  },
  sliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.xs,
  },
  sliderLabel: {
    fontSize: 12,
    color: colors.textLightGray,
    fontFamily: 'NotoSansKR-Regular',
  },
  ingredientGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  ingredientButton: {
    width: '48%',
    borderWidth: 2,
    borderColor: colors.borderGray,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    marginBottom: 10,
  },
  ingredientButtonSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(21, 93, 252, 0.05)',
  },
  ingredientButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textDarkGray,
    fontFamily: 'NotoSansKR-Medium',
  },
  ingredientButtonTextSelected: {
    color: colors.primary,
  },
  descriptionInput: {
    borderWidth: 2,
    borderColor: colors.borderGray,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 5,
    fontSize: 14,
    color: colors.textBlack,
    fontFamily: 'NotoSansKR-Regular',
    height: 100,
    textAlignVertical: 'top',
  },
  charCount: {
    fontSize: 12,
    color: colors.textLightGray,
    fontFamily: 'NotoSansKR-Regular',
    textAlign: 'right',
    marginTop: spacing.xs,
  },
  infoBox: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BEDBFF',
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 13,
    marginBottom: 100,
  },
  infoText: {
    fontSize: 12,
    color: '#193CB8',
    fontFamily: 'NotoSansKR-Regular',
    lineHeight: 18,
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: colors.borderGray,
    paddingHorizontal: spacing.lg,
    paddingTop: 13,
    paddingBottom: spacing.lg,
  },
  createButton: {
    height: 52,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.white,
    fontFamily: 'NotoSansKR-Bold',
  },
});
