import {StyleSheet} from 'react-native';
import {colors, spacing, typography} from '../../common';

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
  },
  modalContainer: {
    width: '100%',
    maxWidth: 327,
    maxHeight: '85%',
    backgroundColor: colors.bgWhite,
    borderRadius: 24,
    paddingTop: 18,
    paddingBottom: 32,
    paddingHorizontal: 32,
    alignItems: 'center',
  },
  scrollContent: {
    width: '100%',
    flexGrow: 1,
  },
  scrollInner: {
    alignItems: 'center',
  },
  iconContainer: {
    width: 80,
    height: 80,
    borderRadius: 80,
    backgroundColor: '#D4F5E9',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
  },
  title: {
    fontSize: 20,
    fontFamily: typography.body.fontFamily,
    color: colors.textDark,
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 28,
  },
  description: {
    fontSize: 13,
    fontFamily: typography.body.fontFamily,
    color: '#6A7282',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 16,
  },
  ingredientSection: {
    width: '100%',
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 12,
    fontFamily: typography.body.fontFamily,
    color: '#6A7282',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  ingredientBox: {
    width: '100%',
    minHeight: 72,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#B9F8CF',
    backgroundColor: '#F8FFF9',
    paddingVertical: 17,
    paddingHorizontal: 17,
  },
  missingBox: {
    width: '100%',
    minHeight: 72,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FFE2E2',
    backgroundColor: '#FFF8F8',
    paddingVertical: 17,
    paddingHorizontal: 17,
  },
  ingredientChipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  availableChip: {
    backgroundColor: colors.bgWhite,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#B9F8CF',
    paddingVertical: 9,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  availableChipText: {
    fontSize: 14,
    fontFamily: typography.body.fontFamily,
    color: '#008236',
    lineHeight: 20,
  },
  missingChip: {
    backgroundColor: colors.bgWhite,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#FFC9C9',
    paddingVertical: 9,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  missingChipText: {
    fontSize: 14,
    fontFamily: typography.body.fontFamily,
    color: '#E7000B',
    lineHeight: 20,
  },
  buttonGroup: {
    width: '100%',
    gap: 12,
    marginTop: 8,
  },
  confirmButton: {
    width: '100%',
    height: 56,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  confirmButtonText: {
    fontSize: 16,
    fontFamily: typography.body.fontFamily,
    color: colors.textWhite,
    lineHeight: 24,
  },
  cancelButton: {
    width: '100%',
    height: 56,
    borderRadius: 14,
    backgroundColor: colors.bgGray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButtonText: {
    fontSize: 16,
    fontFamily: typography.body.fontFamily,
    color: '#364153',
    lineHeight: 24,
  },
});

export default styles;
